# Лабораторная работа № 2. Структуры данных

**Цель:** изучить кортежи, словари, множества и массивы Julia, выполнить
операции над ними и решить задания для самостоятельной работы.

In [1]:
using Pkg
Pkg.activate(joinpath(@__DIR__, ".."))

using Lab02DataTypes
using Primes
using Random
using Statistics

  Activating project at `~/university/static_analys/labs/lab02/project`


## Общие операции и кортежи

In [2]:
empty_tuple = ()
favorite_languages = ("Python", "Julia", "R")
x1 = (1, 2, 3)
x2 = (1, 2.0, "tmp")
x3 = (a=2, b=1 + 2)

println("Пуст ли кортеж: ", isempty(empty_tuple))
println("Длина x2: ", length(x2))
println("Элементы x2: ", (x2[1], x2[2], x2[3]))
println("x1[2] + x1[3] = ", x1[2] + x1[3])
println("Именованный кортеж: ", (x3.a, x3.b, x3[2]))
println("Вхождение: ", (in("tmp", x2), 0 in x2))
println("Уникальные: ", unique((1, 2, 1, 3)))
println("Свёртка и максимум: ", (reduce(+, x1), maximum(x1)))

Пуст ли кортеж: true
Длина x2: 3
Элементы x2: (1, 2.0, "tmp")
x1[2] + x1[3] = 5
Именованный кортеж: (2, 3, 3)
Вхождение: (true, false)
Уникальные: [1, 2, 3]
Свёртка и максимум: (6, 3)


## Словари

In [3]:
phonebook = Dict(
    "Иванов И.И." => ("867-5309", "333-5544"),
    "Бухгалтерия" => "555-2368",
)
println("Ключи: ", collect(keys(phonebook)))
println("Значения: ", collect(values(phonebook)))
println("Пары: ", collect(pairs(phonebook)))
println("Есть Иванов И.И.: ", haskey(phonebook, "Иванов И.И."))
phonebook["Сидоров П.С."] = "555-3344"
removed_phone = pop!(phonebook, "Иванов И.И.")
println("Удалённое значение: ", removed_phone)

dict_a = Dict("foo" => 0.0, "bar" => 42.0)
dict_b = Dict("baz" => 17, "bar" => 13.0)
println("merge(a, b): ", merge(dict_a, dict_b))
println("merge(b, a): ", merge(dict_b, dict_a))

Ключи: ["Бухгалтерия", "Иванов И.И."]
Значения: Any["555-2368", ("867-5309", "333-5544")]
Пары: Pair{String, Any}["Бухгалтерия" => "555-2368", "Иванов И.И." => ("867-5309", "333-5544")]
Есть Иванов И.И.: true
Удалённое значение: ("867-5309", "333-5544")
merge(a, b): Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0)
merge(b, a): Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0)


## Множества

In [4]:
S1 = Set([1, 2])
S2 = Set([3, 4])
S3 = Set([1, 2, 2, 3, 1, 2, 3, 2, 1])
S4 = Set([2, 3, 1])

println("Эквивалентность S1 и S2: ", issetequal(S1, S2))
println("Эквивалентность S3 и S4: ", issetequal(S3, S4))
println("Объединение: ", union(S1, S2))
println("Пересечение: ", intersect(S1, S3))
println("Разность: ", setdiff(S3, S1))
println("Включение: ", issubset(S1, S4))
push!(S4, 99)
println("После push!: ", S4)

Эквивалентность S1 и S2: false
Эквивалентность S3 и S4: true
Объединение: Set([4, 2, 3, 1])
Пересечение: Set([2, 1])
Разность: Set([3])
Включение: true
После push!: Set([2, 99, 3, 1])


## Массивы

In [5]:
empty_array_1 = []
empty_array_2 = Int64[]
empty_array_3 = Float64[]
column_vector = [1, 2, 3]
row_vector = [1 2 3]
matrix_A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]
matrix_B = [[1 2 3]; [4 5 6]; [7 8 9]]

println("Вектор-столбец: ", column_vector)
println("Вектор-строка: ", row_vector)
display(matrix_A)
display(matrix_B)

rng = MersenneTwister(2026)
println("Случайный массив 1×8: ", rand(rng, 1, 8))
println("Случайный массив 2×3: ", rand(rng, 2, 3))
println("Размер массива 4×3×2: ", size(rand(rng, 4, 3, 2)))

roots = [sqrt(i) for i in 1:10]
ar_1 = [3i^2 for i in 1:2:9]
ar_2 = [i^2 for i in 1:10 if i^2 % 5 != 0 && i^2 % 4 != 0]
println("Корни: ", roots)
println("3i²: ", ar_1)
println("Квадраты по условию: ", ar_2)

base = collect(1:12)
reshaped = reshape(base, (2, 6))
ar = rand(rng, 10:20, 10, 5)
println("length, ndims, size: ", (length(ar), ndims(ar), size(ar)))
println("ones: ", ones(2, 3))
println("zeros: ", zeros(4))
println("fill: ", fill(3.5, (3, 2)))
println("repeat: ", repeat([1, 2], 3, 3))
display(reshaped)
display(transpose(reshaped))
println("Второй столбец: ", ar[:, 2])
println("Столбцы 2 и 5: ", ar[:, [2, 5]])
println("Столбцы 2:4: ", ar[:, 2:4])
println("Выбранные строки и столбцы: ", ar[[2, 4, 6], [1, 5]])
println("Срез первой строки: ", ar[1, 3:end])
display(sort(ar, dims=1))
display(sort(ar, dims=2))
display(ar .> 14)
println("Индексы значений > 14: ", findall(ar .> 14))

Вектор-столбец: [1, 2, 3]
Вектор-строка: [1 2 3]
Случайный массив 1×8: [0.8513569836272035 0.3863230577926433 0.47892345399711855 0.04608452364256488 0.9654217070878959 0.4094887305047312 0.4116951388655894 0.10120088817622075]
Случайный массив 2×3: [0.6445376728696182 0.6860151442610469 0.5857226048957671; 0.01764043989956421 0.9227358310012015 0.6499857173655867]
Размер массива 4×3×2: (4, 3, 2)
Корни: [1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178, 2.6457513110645907, 2.8284271247461903, 3.0, 3.1622776601683795]
3i²: [3, 27, 75, 147, 243]
Квадраты по условию: [1, 9, 49, 81]
length, ndims, size: (50, 2, (10, 5))
ones: [1.0 1.0 1.0; 1.0 1.0 1.0]
zeros: [0.0, 0.0, 0.0, 0.0]
fill: [3.5 3.5; 3.5 3.5; 3.5 3.5]
repeat: [1 1 1; 2 2 2; 1 1 1; 2 2 2; 1 1 1; 2 2 2]
Второй столбец: [10, 10, 11, 13, 13, 11, 12, 20, 17, 12]
Столбцы 2 и 5: [10 13; 10 10; 11 12; 13 10; 13 20; 11 13; 12 11; 20 13; 17 19; 12 10]
Столбцы 2:4: [10 19 14; 10 17 14; 11 18 14; 13 11 

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

10×5 Matrix{Int64}:
 10  10  11  10  10
 12  10  11  10  10
 12  11  11  13  10
 14  11  12  14  11
 14  12  15  14  12
 14  12  15  14  13
 16  13  16  15  13
 16  13  17  15  13
 16  17  18  16  19
 20  20  19  18  20

10×5 Matrix{Int64}:
 10  13  14  16  19
 10  10  12  14  17
 11  12  14  16  18
 10  11  13  15  16
 11  13  14  15  20
 10  11  13  14  15
 10  10  11  12  12
 11  13  14  16  20
 12  16  17  18  19
 10  12  13  15  20

10×5 BitMatrix:
 1  0  1  0  0
 0  0  1  0  0
 1  0  1  0  0
 1  0  0  1  0
 0  0  0  1  1
 0  0  1  0  0
 0  0  0  0  0
 0  1  0  1  0
 0  1  1  1  1
 1  0  1  0  0

## Самостоятельные задания 1–2

In [6]:
sets = set_task()
println("P = ", sort(collect(sets.P)))
println("Операции над множествами разных типов: ", sets.examples)

P = [0, 1, 3, 4, 7, 9]
Операции над множествами разных типов: (union = Set([5.0, 2.0, 3.5, 3.0, 1.0]), intersection = Set([5.0, 2.0]), difference = Set(Any[3.5, "Julia"]), membership = true, subset = true)


## Самостоятельные задания 3.1–3.13

In [7]:
arrays = array_tasks(N=25)
println("3.1: ", arrays.ascending)
println("3.2: ", arrays.descending)
println("3.3: ", arrays.there_and_back)
println("3.4: ", arrays.tmp)
println("3.5: ", arrays.first_ten)
println("3.6: ", arrays.all_ten)
println("3.7: ", arrays.counts_11_10_10)
println("3.8: ", arrays.blocks_10_20_30)
println("3.9: ", arrays.powers)
println("Количество цифр 6: ", arrays.six_digits)
println("3.10, y: ", arrays.y_grid)
println("Среднее y: ", arrays.y_mean)
println("3.11: ", arrays.power_pairs)
println("3.12: ", arrays.ratio_powers)
println("3.13: ", arrays.filenames)

3.1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
3.2: [25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
3.3: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
3.4: [4, 6, 3]
3.5: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]
3.6: [4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]
3.7: [4, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]
3.8: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
3.9: [16, 64, 8, 8, 8, 8]
Количество цифр 6: 2
3.10, y: [-19.884530844146987, -22.178753389342127, -24.490696732801293, -26.77318244299338, -28.969237768093574, -31.011186439374516, -32.8197

## Самостоятельное задание 3.14

In [8]:
randoms = random_vector_tasks(seed=2026, n=250)
println("Вектор разностей: ", randoms.differences)
println("Линейная комбинация: ", randoms.linear_combination)
println("Тригонометрические отношения: ", randoms.trig_ratios)
println("Сумма: ", randoms.weighted_sum)
println("y > 600: ", randoms.y_over_600)
println("Индексы y > 600: ", randoms.over_600_indices)
println("Соответствующие x: ", randoms.corresponding_x)
println("Корни отклонений: ", randoms.deviations)
println("Не далее 200 от max(y): ", randoms.near_max_count)
println("Чётных/нечётных: ", (randoms.even_count, randoms.odd_count))
println("Кратных 7: ", randoms.multiples_of_7)
println("x по возрастанию y: ", randoms.x_sorted_by_y)
println("top-10 x: ", randoms.x_top_10)
println("Уникальные x: ", randoms.unique_x)

Вектор разностей: [-103, 211, -313, 132, -386, 65, 423, 236, 247, 119, 320, -193, -1, 637, -892, 377, -155, 500, -309, 324, -201, 175, 110, 636, -52, 708, 285, 3, 637, -953, -48, -213, -308, 127, 258, -200, -597, -200, 175, -251, 632, -310, 381, 503, -452, 466, 286, 274, -412, -50, -77, 537, 103, -450, -281, -606, 464, 339, 26, 430, -105, -84, 672, -575, 510, -173, 44, -41, 377, -414, -224, 133, 123, 832, -79, 198, 379, -21, 588, -575, 304, 787, 256, 162, 851, -439, 235, 18, 89, 875, 506, 56, -340, -836, -95, 602, -144, -195, 634, 92, 259, 653, 850, -93, -116, -50, 477, -896, -248, 64, -15, -708, 185, 215, -136, -541, 646, 154, -335, -218, -304, 784, -272, -163, -846, 287, 340, -324, 359, -391, 546, -661, -179, -69, 711, -63, -131, 153, 33, -161, 773, 132, -419, 266, 84, -650, 110, 138, -107, -491, -160, 595, -653, 373, -871, -193, -102, 106, 396, -323, 907, 74, -943, -805, -450, -122, 63, -84, -180, 85, 536, -566, 191, 245, -582, 740, 100, 268, 214, -415, -698, 34, -414, -355, -287, -

## Самостоятельные задания 4–6

In [9]:
sequences = squares_and_primes()
println("Квадраты 1:100: ", sequences.squares)
println("Первые 168 простых: ", sequences.myprimes)
println("89-е простое: ", sequences.prime_89)
println("Простые 89:99: ", sequences.primes_89_to_99)

sums = sums_task(M=25)
println("6.1: ", sums.sum_6_1)
println("6.2: ", sums.sum_6_2)
println("Члены 6.3: ", sums.terms_6_3)
println("6.3: ", sums.sum_6_3)

Квадраты 1:100: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]
Первые 168 простых: [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449

## Вывод

Изучены основные структуры данных Julia и операции над ними. Все случайные
примеры воспроизводимы, а решения самостоятельных заданий вынесены в модуль и
проверяются автоматическими тестами.