In [1]:
ENV["LAB04_TASK"] = "all"

"all"

# Лабораторная работа № 4

**Тема:** Линейная алгебра в Julia.

**Цель:** изучить операции линейной алгебры, факторизации, специальные
матричные структуры и оценку эффективности вычислений.

In [2]:
using DrWatson
@quickactivate "project"

using BenchmarkTools
using LinearAlgebra
using Random
using Statistics

include(srcdir("lab04.jl"))
using .Lab04

Random.seed!(20261010)

function heading(title)
    println("\n", repeat("=", 78))
    println(title)
    println(repeat("=", 78))
end

function print_system_result(label, coefficients, right_side)
    result = solve_exact(coefficients, right_side)
    descriptions = Dict(
        :unique => "единственное решение",
        :infinite => "бесконечно много решений",
        :inconsistent => "решений нет",
    )
    println("\n", label, ": ", descriptions[result.kind])
    println("rank(A) = ", result.rank_a, ", rank([A|b]) = ", result.rank_augmented)
    println("RREF([A|b]) =")
    display(result.rref)
    if result.kind != :inconsistent
        println("Частное решение: ", result.particular)
        if result.kind == :infinite
            println("Базис однородных решений: ", result.null_basis)
            println("Общий вид: x = x₀ + Σ tᵢ nᵢ")
        end
    end
    return result
end

print_system_result (generic function with 1 method)

## 4.2.1. Поэлементные операции над многомерными массивами

In [3]:
function run_4_2_1()
heading("4.2.1. Поэлементные операции")
a = rand(1:20, (4, 3))
println("a ="); display(a)
println("sum(a) = ", sum(a))
println("Суммы по столбцам:"); display(sum(a; dims=1))
println("Суммы по строкам:"); display(sum(a; dims=2))
println("prod(a) = ", prod(a))
println("Произведения по столбцам:"); display(prod(a; dims=1))
println("Произведения по строкам:"); display(prod(a; dims=2))
println("mean(a) = ", mean(a))
println("Средние по столбцам:"); display(mean(a; dims=1))
println("Средние по строкам:"); display(mean(a; dims=2))
end

run_4_2_1 (generic function with 1 method)

## 4.2.2. Транспонирование, след, ранг, определитель и инверсия

In [4]:
function run_4_2_2()
heading("4.2.2. Основные матричные операции")
function random_nonsingular_matrix(size; values=1:20)
    while true
        candidate = rand(values, (size, size))
        !iszero(det(candidate)) && return candidate
    end
end
b = random_nonsingular_matrix(4)
println("b ="); display(b)
println("transpose(b) ="); display(transpose(b))
println("tr(b) = ", tr(b))
println("diag(b) = ", diag(b))
println("rank(b) = ", rank(b))
println("inv(b) ="); display(inv(b))
println("det(b) = ", det(b))
    a = rand(1:20, (4, 3))
println("pinv(a) ="); display(pinv(a))
end

run_4_2_2 (generic function with 1 method)

## 4.2.3. Нормы, расстояние, угол и повороты

In [5]:
function run_4_2_3()
heading("4.2.3. Нормы, расстояние, угол и повороты")
X = [2, 4, -5]
Y = [1, -1, 3]
println("norm(X) = ", norm(X))
println("norm(X, 1) = ", norm(X, 1))
println("norm(X - Y) = ", norm(X - Y))
println("Проверка расстояния = ", sqrt(sum((X - Y) .^ 2)))
angle = acos(clamp(dot(X, Y) / (norm(X) * norm(Y)), -1, 1))
println("Угол X и Y, рад = ", angle)

d = [5 -4 2; -1 2 3; -2 1 0]
println("d ="); display(d)
println("opnorm(d) = ", opnorm(d))
println("opnorm(d, 1) = ", opnorm(d, 1))
println("rot180(d) ="); display(rot180(d))
println("reverse(d, dims=1) ="); display(reverse(d; dims=1))
println("reverse(d, dims=2) ="); display(reverse(d; dims=2))
end

run_4_2_3 (generic function with 1 method)

## 4.2.4. Матричное умножение и скалярное произведение

In [6]:
function run_4_2_4()
heading("4.2.4. Умножение матриц и векторов")
A_product = rand(1:10, (2, 3))
B_product = rand(1:10, (3, 4))
X = [2, 4, -5]
Y = [1, -1, 3]
println("A * B ="); display(A_product * B_product)
println("Единичная матрица ="); display(Matrix{Int}(I, 3, 3))
println("dot(X, Y) = ", dot(X, Y))
println("X'Y = ", X'Y)
end

run_4_2_4 (generic function with 1 method)

## 4.2.5. Факторизации и специальные матричные структуры

In [7]:
function run_4_2_5()
heading("4.2.5. Факторизации")
A_factor = rand(3, 3)
x_known = fill(1.0, 3)
b_factor = A_factor * x_known
println("Решение A \\ b = ", A_factor \ b_factor)

A_lu = lu(A_factor)
println("Матрица перестановок P ="); display(A_lu.P)
println("Вектор перестановок p = ", A_lu.p)
println("L ="); display(A_lu.L)
println("U ="); display(A_lu.U)
println("Решение через LU = ", A_lu \ b_factor)
println("det(A) = ", det(A_factor), ", det(lu(A)) = ", det(A_lu))
println("Проверка P*A ≈ L*U: ", A_lu.P * A_factor ≈ A_lu.L * A_lu.U)

A_qr = qr(A_factor)
Q = Matrix(A_qr.Q)
R = A_qr.R
println("Q ="); display(Q)
println("R ="); display(R)
println("Q'Q ≈ I: ", Q' * Q ≈ I)
println("Q*R ≈ A: ", Q * R ≈ A_factor)

A_symmetric = A_factor + A_factor'
A_eigen = eigen(Symmetric(A_symmetric))
println("Собственные значения = ", A_eigen.values)
println("Собственные векторы ="); display(A_eigen.vectors)
println("V*Λ*V' ≈ A: ", A_eigen.vectors * Diagonal(A_eigen.values) * A_eigen.vectors' ≈ A_symmetric)

#= Пример из пособия использует матрицу 1000×1000. Число замеров уменьшено до
одного, чтобы сценарий удобно было повторять во время защиты. =#
n_dense = 1000
A_dense = randn(n_dense, n_dense)
A_dense_symmetric = A_dense + A_dense'
A_dense_noisy = copy(A_dense_symmetric)
A_dense_noisy[1, 2] += 5eps()
A_dense_explicit = Symmetric(A_dense_noisy)
println("issymmetric(A_dense_symmetric) = ", issymmetric(A_dense_symmetric))
println("issymmetric(A_dense_noisy) = ", issymmetric(A_dense_noisy))

dense_symmetric_time = @belapsed eigvals($A_dense_symmetric) samples=1 evals=1
dense_noisy_time = @belapsed eigvals($A_dense_noisy) samples=1 evals=1
dense_explicit_time = @belapsed eigvals($A_dense_explicit) samples=1 evals=1
println("eigvals симметричной матрицы: ", dense_symmetric_time, " с")
println("eigvals зашумлённой матрицы: ", dense_noisy_time, " с")
println("eigvals с явным Symmetric: ", dense_explicit_time, " с")

n_tridiagonal = 1_000_000
A_tridiagonal = SymTridiagonal(randn(n_tridiagonal), randn(n_tridiagonal - 1))
tridiagonal_time = @belapsed eigmax($A_tridiagonal) samples=1 evals=1
println("eigmax SymTridiagonal 1_000_000×1_000_000: ", tridiagonal_time, " с")
println("Плотная версия потребовала бы примерно ",
    round(n_tridiagonal^2 * sizeof(Float64) / 1024^4; digits=2), " ТиБ памяти и не создаётся.")
end

run_4_2_5 (generic function with 1 method)

## 4.2.6. Общая линейная алгебра

In [8]:
function run_4_2_6()
heading("4.2.6. Рациональная линейная алгебра")
A_rational = Rational{BigInt}.(rand(1:10, 3, 3)) ./ 10
x_rational = fill(BigInt(1), 3)
b_rational = A_rational * x_rational
println("A_rational ="); display(A_rational)
println("Точное решение = ", A_rational \ b_rational)
println("LU для рациональной матрицы = "); display(lu(A_rational))
end

run_4_2_6 (generic function with 1 method)

## 4.4.1. Произведение векторов

In [9]:
function run_4_4_1()
heading("4.4.1. Произведение векторов")
v = [1, 2, 3]
dot_v = dot(v, v)
outer_v = v * v'
println("v = ", v)
println("dot_v = v⋅v = ", dot_v)
println("outer_v = v*v' ="); display(outer_v)
end

run_4_4_1 (generic function with 1 method)

## 4.4.2. Системы линейных уравнений

In [10]:
function run_4_4_2_1()
heading("4.4.2. СЛАУ с двумя неизвестными")
systems_two = [
    ("a", [1 1; 1 -1], [2, 3]),
    ("b", [1 1; 2 2], [2, 4]),
    ("c", [1 1; 2 2], [2, 5]),
    ("d", [1 1; 2 2; 3 3], [1, 2, 3]),
    ("e", [1 1; 2 1; 1 -1], [2, 1, 3]),
    ("f", [1 1; 2 1; 3 2], [2, 1, 3]),
]
for (label, coefficients, right_side) in systems_two
    print_system_result(label, coefficients, right_side)
end
end

function run_4_4_2_2()
heading("4.4.2. СЛАУ с тремя неизвестными")
systems_three = [
    ("a", [1 1 1; 1 -1 -2], [2, 3]),
    ("b", [1 1 1; 2 2 -3; 3 1 1], [2, 4, 1]),
    ("c", [1 1 1; 1 1 2; 2 2 3], [1, 0, 1]),
    ("d", [1 1 1; 1 1 2; 2 2 3], [1, 0, 0]),
]
for (label, coefficients, right_side) in systems_three
    print_system_result(label, coefficients, right_side)
end
end

run_4_4_2_2 (generic function with 1 method)

## 4.4.3. Операции с матрицами

In [11]:
function run_4_4_3_1()
heading("4.4.3.1. Диагонализация")
matrices_to_diagonalize = [
    ("a", [1 -2; -2 1]),
    ("b", [1 -2; -2 3]),
    ("c", [1 -2 0; -2 1 2; 0 2 0]),
]
for (label, matrix) in matrices_to_diagonalize
    decomposition = eigen(Symmetric(Float64.(matrix)))
    diagonal = Diagonal(decomposition.values)
    residual = norm(matrix * decomposition.vectors - decomposition.vectors * diagonal)
    println("\n", label, ") A ="); display(matrix)
    println("D ="); display(diagonal)
    println("P (столбцы — собственные векторы) ="); display(decomposition.vectors)
    println("Проверка A*P ≈ P*D, невязка = ", residual)
end
end

function run_4_4_3_2()
heading("4.4.3.2. Степень и корни матриц")
power_source = [1 -2; -2 1]
power_10 = power_source^10
println("a) [1 -2; -2 1]^10 ="); display(power_10)

square_source_1 = [5 -2; -2 5]
square_root_1 = matrix_function_symmetric(square_source_1, sqrt)
println("b) sqrt([5 -2; -2 5]) ="); display(square_root_1)
println("Проверка R^2 ≈ A: ", square_root_1^2 ≈ square_source_1)

cube_source = [1 -2; -2 1]
cube_root = matrix_function_symmetric(cube_source, cbrt)
println("c) cbrt([1 -2; -2 1]) ="); display(cube_root)
println("Проверка R^3 ≈ A: ", cube_root^3 ≈ cube_source)

square_source_2 = [1 2; 2 3]
square_root_2 = matrix_function_symmetric(square_source_2, value -> sqrt(complex(value)))
println("d) Главный комплексный sqrt([1 2; 2 3]) ="); display(square_root_2)
println("Комплексный результат нужен из-за отрицательного собственного значения.")
println("Проверка R^2 ≈ A: ", square_root_2^2 ≈ square_source_2)
end

function run_4_4_3_3()
heading("4.4.3.3. Собственные значения и эффективность")
large_A = [
    140 97 74 168 131
    97 106 89 131 36
    74 89 152 144 71
    168 131 144 54 142
    131 36 71 142 36
]
large_eigenvalues = eigvals(Symmetric(large_A))
eigenvalue_diagonal = Diagonal(large_eigenvalues)
lower_triangular = LowerTriangular(large_A)
println("Собственные значения A = ", large_eigenvalues)
println("Диагональная матрица собственных значений ="); display(eigenvalue_diagonal)
println("Нижнетреугольная часть A ="); display(lower_triangular)

time_eigenvalues = @belapsed eigvals(Symmetric($large_A))
time_diagonal = @belapsed Diagonal($large_eigenvalues)
time_lower = @belapsed LowerTriangular($large_A)
println("Время eigvals: ", time_eigenvalues, " с")
println("Время создания Diagonal: ", time_diagonal, " с")
println("Время создания LowerTriangular: ", time_lower, " с")
end

run_4_4_3_3 (generic function with 1 method)

## 4.4.4. Линейные модели экономики

In [12]:
function print_inverse_productivity(label, matrix; direct=false)
    productive, leontief_inverse = productivity_by_inverse(matrix)
    println("\n", label, ") A ="); display(matrix)
    println("(I-A)^(-1) ="); display(leontief_inverse)
    println("Матрица ", productive ? "продуктивна" : "непродуктивна")
    if direct && !productive
        negative_position = findfirst(value -> value < -1e-12, leontief_inverse)
        input_column = negative_position[2]
        y = zeros(size(matrix, 1)); y[input_column] = 1
        x = leontief_inverse * y
        println("Контрпример по определению: y = ", y, ", x = ", x)
    end
end

function run_4_4_4_1()
heading("4.4.4.1. Проверка продуктивности по определению")
definition_matrices = [
    ("a", [1.0 2.0; 3.0 4.0]),
    ("b", (1 / 2) .* [1.0 2.0; 3.0 4.0]),
    ("c", (1 / 10) .* [1.0 2.0; 3.0 4.0]),
]
for (label, matrix) in definition_matrices
    print_inverse_productivity(label, matrix; direct=true)
end
end

function run_4_4_4_2()
heading("4.4.4.2. Критерий неотрицательности (I-A)^(-1)")
inverse_criterion_matrices = [
    ("a", [1.0 2.0; 3.0 1.0]),
    ("b", (1 / 2) .* [1.0 2.0; 3.0 1.0]),
    ("c", (1 / 10) .* [1.0 2.0; 3.0 1.0]),
]
for (label, matrix) in inverse_criterion_matrices
    print_inverse_productivity(label, matrix)
end
end

function run_4_4_4_3()
heading("4.4.4.3. Спектральный критерий")
spectral_matrices = [
    ("a", [1.0 2.0; 3.0 1.0]),
    ("b", (1 / 2) .* [1.0 2.0; 3.0 1.0]),
    ("c", (1 / 10) .* [1.0 2.0; 3.0 1.0]),
    ("d", [0.1 0.2 0.3; 0.0 0.1 0.2; 0.0 0.1 0.3]),
]
for (label, matrix) in spectral_matrices
    values = eigvals(matrix)
    radius = maximum(abs.(values))
    println("\n", label, ") λ = ", values)
    println("Спектральный радиус ρ(A) = ", radius)
    println("Матрица ", radius < 1 ? "продуктивна" : "непродуктивна")
end
end

run_4_4_4_3 (generic function with 1 method)

## Вывод

Выполнены все примеры и самостоятельные задания: изучены операции с векторами
и матрицами, точное решение и классификация СЛАУ, диагонализация, матричные
функции, факторизации, специальные структуры, бенчмаркинг и три критерия
продуктивности линейных моделей экономики.

In [13]:
const TASKS = [
    "4.2.1" => run_4_2_1,
    "4.2.2" => run_4_2_2,
    "4.2.3" => run_4_2_3,
    "4.2.4" => run_4_2_4,
    "4.2.5" => run_4_2_5,
    "4.2.6" => run_4_2_6,
    "4.4.1" => run_4_4_1,
    "4.4.2.1" => run_4_4_2_1,
    "4.4.2.2" => run_4_4_2_2,
    "4.4.3.1" => run_4_4_3_1,
    "4.4.3.2" => run_4_4_3_2,
    "4.4.3.3" => run_4_4_3_3,
    "4.4.4.1" => run_4_4_4_1,
    "4.4.4.2" => run_4_4_4_2,
    "4.4.4.3" => run_4_4_4_3,
]

requested_task = get(ENV, "LAB04_TASK", "all")
if requested_task == "all"
    for (_, run_task) in TASKS
        run_task()
    end
    heading("Лабораторная работа № 4 выполнена полностью")
else
    task_index = findfirst(pair -> first(pair) == requested_task, TASKS)
    isnothing(task_index) && error(
        "Неизвестное задание '$requested_task'. Доступны: " *
        join(first.(TASKS), ", "),
    )
    last(TASKS[task_index])()
    heading("Задание $requested_task выполнено")
end


4.2.1. Поэлементные операции
a =


4×3 Matrix{Int64}:
  8  11  11
 16  19  20
 15  15   8
  6   2   6

sum(a) = 137


Суммы по столбцам:


1×3 Matrix{Int64}:
 45  47  45

Суммы по строкам:


4×1 Matrix{Int64}:
 30
 55
 38
 14

prod(a) = 762753024000
Произведения по столбцам:


1×3 Matrix{Int64}:
 11520  6270  10560

Произведения по строкам:


4×1 Matrix{Int64}:
  968
 6080
 1800
   72

mean(a) = 11.416666666666666
Средние по столбцам:


1×3 Matrix{Float64}:
 11.25  11.75  11.25

Средние по строкам:


4×1 Matrix{Float64}:
 10.0
 18.333333333333332
 12.666666666666666
  4.666666666666667


4.2.2. Основные матричные операции
b =


4×4 Matrix{Int64}:
 12  20  18  13
  4   7   3   9
 13  18  16  11
 14  18   6   9

transpose(b) =


4×4 transpose(::Matrix{Int64}) with eltype Int64:
 12  4  13  14
 20  7  18  18
 18  3  16   6
 13  9  11   9

tr(b) = 44
diag(b) = 

[12, 7, 16, 9]
rank(b) = 4
inv(b) =


4×4 Matrix{Float64}:
 -0.447637    0.0611677   0.503244  -0.0296571
  0.412882   -0.137164   -0.492122   0.142261
 -0.0217794  -0.034291    0.126969  -0.0894347
 -0.114921    0.202039    0.116775  -0.0676552

det(b) = 2157.999999999999
pinv(a) =


3×4 Matrix{Float64}:
 -0.0578073   0.0376951   0.0539671   0.0116135
  0.117764   -0.128356   -0.0104072   0.014593
 -0.0387807   0.103893   -0.0190696  -0.00839392


4.2.3. Нормы, расстояние, угол и повороты
norm(X) = 6.708203932499369
norm(X, 1) = 11.0
norm(X - Y) = 9.486832980505138
Проверка расстояния = 9.486832980505138
Угол X и Y, рад = 2.4404307889469252
d =


3×3 Matrix{Int64}:
  5  -4  2
 -1   2  3
 -2   1  0

opnorm(d) = 7.147682841795258
opnorm(d, 1) = 8.0
rot180(d) =


3×3 Matrix{Int64}:
 0   1  -2
 3   2  -1
 2  -4   5

reverse(d, dims=1) =


3×3 Matrix{Int64}:
 -2   1  0
 -1   2  3
  5  -4  2

reverse(d, dims=2) =


3×3 Matrix{Int64}:
 2  -4   5
 3   2  -1
 0   1  -2


4.2.4. Умножение матриц и векторов
A * B =


2×4 Matrix{Int64}:
  68  74  140  53
 108  98  162  78

Единичная матрица =


3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

dot(X, Y) = -17
X'Y = -17



4.2.5. Факторизации
Решение A \ b = 

[0.9999999999999999, 1.0000000000000002, 1.0]
Матрица перестановок P =


3×3 Matrix{Float64}:
 0.0  0.0  1.0
 1.0  0.0  0.0
 0.0  1.0  0.0

Вектор перестановок p = [3, 1, 2]
L =


3×3 Matrix{Float64}:
 1.0        0.0       0.0
 0.0709437  1.0       0.0
 0.451986   0.742969  1.0

U =


3×3 Matrix{Float64}:
 0.768316  0.199021   0.56907
 0.0       0.397117   0.604955
 0.0       0.0       -0.280719

Решение через LU = [0.9999999999999999, 1.0000000000000002, 1.0]
det(A) = -0.08565049049731605, det(lu(A)) = -0.08565049049731605
Проверка P*A ≈ L*U: true
Q =


3×3 Matrix{Float64}:
 -0.0645123  -0.820548  -0.567926
 -0.411011   -0.496751   0.764401
 -0.909345    0.282737  -0.305208

R =


3×3 Matrix{Float64}:
 -0.844911  -0.365749  -0.734185
  0.0       -0.472418  -0.580218
  0.0        0.0       -0.214582

Q'Q ≈ I: true
Q*R ≈ A: true
Собственные значения = [-0.9299272493759569, 0.32869340678955705, 2.618390338279227]
Собственные векторы =


3×3 Matrix{Float64}:
 -0.836497   0.107625  0.537299
  0.183401  -0.868987  0.459593
  0.516369   0.482989  0.707167

V*Λ*V' ≈ A: true
issymmetric(A_dense_symmetric) = true
issymmetric(A_dense_noisy) = false
eigvals симметричной матрицы: 

0.053462797 с
eigvals зашумлённой матрицы: 0.379344791 с
eigvals с явным Symmetric: 0.05101131 с
eigmax SymTridiagonal 1_000_000×1_000_000: 

0.405397508 с
Плотная версия потребовала бы примерно 7.28 ТиБ памяти и не создаётся.



4.2.6. Рациональная линейная алгебра
A_rational =


3×3 Matrix{Rational{BigInt}}:
 4//5    1    1//2
 1//10  2//5  2//5
 9//10  1//5   1

Точное решение = Rational{BigInt}

[1, 1, 1]
LU для рациональной матрицы = 


LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
  1      0     0
 8//9    1     0
 1//9  17//37  1
U factor:
3×3 Matrix{Rational{BigInt}}:
 9//10   1//5      1
  0     37//45   -7//18
  0       0     173//370


4.4.1. Произведение векторов
v = [1, 2, 3]
dot_v = v⋅v = 14
outer_v = v*v' =


3×3 Matrix{Int64}:
 1  2  3
 2  4  6
 3  6  9


4.4.2. СЛАУ с двумя неизвестными

a: единственное решение
rank(A) = 2, rank([A|b]) = 2
RREF([A|b]) =


2×3 Matrix{Rational{BigInt}}:
 1  0   5//2
 0  1  -1//2

Частное решение: Rational{BigInt}[5//2, -1//2]

b: бесконечно много решений
rank(A) = 1, rank([A|b]) = 1
RREF([A|b]) =


2×3 Matrix{Rational{BigInt}}:
 1  1  2
 0  0  0

Частное решение: Rational{BigInt}[2, 0]
Базис однородных решений: 

Vector{Rational{BigInt}}[[-1, 1]]
Общий вид: x = x₀ + Σ tᵢ nᵢ

c: решений нет
rank(A) = 1, rank([A|b]) = 2
RREF([A|b]) =


2×3 Matrix{Rational{BigInt}}:
 1  1  0
 0  0  1


d: бесконечно много решений
rank(A) = 1, rank([A|b]) = 1
RREF([A|b]) =


3×3 Matrix{Rational{BigInt}}:
 1  1  1
 0  0  0
 0  0  0

Частное решение: Rational{BigInt}[1, 0]
Базис однородных решений: Vector{Rational{BigInt}}[[-1, 1]]
Общий вид: x = x₀ + Σ tᵢ nᵢ

e: решений нет
rank(A) = 2, rank([A|b]) = 3
RREF([A|b]) =


3×3 Matrix{Rational{BigInt}}:
 1  0  0
 0  1  0
 0  0  1


f: единственное решение
rank(A) = 2, rank([A|b]) = 2
RREF([A|b]) =


3×3 Matrix{Rational{BigInt}}:
 1  0  -1
 0  1   3
 0  0   0

Частное решение: Rational{BigInt}[-1, 3]

4.4.2. СЛАУ с тремя неизвестными

a: бесконечно много решений
rank(A) = 2, rank([A|b]) = 2
RREF([A|b]) =


2×4 Matrix{Rational{BigInt}}:
 1  0  -1//2   5//2
 0  1   3//2  -1//2

Частное решение: Rational{BigInt}[5//2, -1//2, 0]
Базис однородных решений: Vector{Rational{BigInt}}[[1//2, -3//2, 1]]
Общий вид: x = x₀ + Σ tᵢ nᵢ

b: единственное решение
rank(A) = 3, rank([A|b]) = 3
RREF([A|b]) =


3×4 Matrix{Rational{BigInt}}:
 1  0  0  -1//2
 0  1  0   5//2
 0  0  1    0

Частное решение: Rational{BigInt}[-1//2, 5//2, 0]

c: бесконечно много решений
rank(A) = 2, rank([A|b]) = 2
RREF([A|b]) =


3×4 Matrix{Rational{BigInt}}:
 1  1  0   2
 0  0  1  -1
 0  0  0   0

Частное решение: Rational{BigInt}[2, 0, -1]
Базис однородных решений: Vector{Rational{BigInt}}[[-1, 1, 0]]
Общий вид: x = x₀ + Σ tᵢ nᵢ

d: решений нет
rank(A) = 2, rank([A|b]) = 3
RREF([A|b]) =


3×4 Matrix{Rational{BigInt}}:
 1  1  0  0
 0  0  1  0
 0  0  0  1


4.4.3.1. Диагонализация

a) A =


2×2 Matrix{Int64}:
  1  -2
 -2   1

D =


2×2 Diagonal{Float64, Vector{Float64}}:
 -1.0   ⋅ 
   ⋅   3.0

P (столбцы — собственные векторы) =


2×2 Matrix{Float64}:
 -0.707107  -0.707107
 -0.707107   0.707107

Проверка A*P ≈ P*D, невязка = 0.0

b) A =


2×2 Matrix{Int64}:
  1  -2
 -2   3

D =


2×2 Diagonal{Float64, Vector{Float64}}:
 -0.236068   ⋅ 
   ⋅        4.23607

P (столбцы — собственные векторы) =


2×2 Matrix{Float64}:
 -0.850651  -0.525731
 -0.525731   0.850651

Проверка A*P ≈ P*D, невязка = 7.121076845233165e-16

c) A =


3×3 Matrix{Int64}:
  1  -2  0
 -2   1  2
  0   2  0

D =


3×3 Diagonal{Float64, Vector{Float64}}:
 -2.14134   ⋅         ⋅ 
   ⋅       0.515138   ⋅ 
   ⋅        ⋅        3.6262

P (столбцы — собственные векторы) =


3×3 Matrix{Float64}:
  0.421859  0.717093   0.554808
  0.6626    0.173846  -0.728518
 -0.618866  0.674948  -0.401808

Проверка A*P ≈ P*D, невязка = 7.179847579402122e-15



4.4.3.2. Степень и корни матриц
a) [1 -2; -2 1]^10 =


2×2 Matrix{Int64}:
  29525  -29524
 -29524   29525

b) sqrt([5 -2; -2 5]) =


2×2 Matrix{Float64}:
  2.1889   -0.45685
 -0.45685   2.1889

Проверка R^2 ≈ A: true
c) cbrt([1 -2; -2 1]) =


2×2 Matrix{Float64}:
  0.221125  -1.22112
 -1.22112    0.221125

Проверка R^3 ≈ A: true
d) Главный комплексный sqrt([1 2; 2 3]) =

2×2 Matrix{ComplexF64}:
 0.568864+0.351578im  0.920442-0.217287im
 0.920442-0.217287im   1.48931+0.134291im

Комплексный результат нужен из-за отрицательного собственного значения.


Проверка R^2 ≈ A: true



4.4.3.3. Собственные значения и эффективность
Собственные значения A = [-128.49322764802145, -55.88778455305688, 42.75216727931894, 87.16111477514521, 542.4677301466143]
Диагональная матрица собственных значений =


5×5 Diagonal{Float64, Vector{Float64}}:
 -128.493     ⋅        ⋅        ⋅         ⋅ 
     ⋅     -55.8878    ⋅        ⋅         ⋅ 
     ⋅        ⋅      42.7522    ⋅         ⋅ 
     ⋅        ⋅        ⋅      87.1611     ⋅ 
     ⋅        ⋅        ⋅        ⋅      542.468

Нижнетреугольная часть A =


5×5 LowerTriangular{Int64, Matrix{Int64}}:
 140    ⋅    ⋅    ⋅   ⋅
  97  106    ⋅    ⋅   ⋅
  74   89  152    ⋅   ⋅
 168  131  144   54   ⋅
 131   36   71  142  36

Время eigvals: 1.201e-6

 с
Время создания Diagonal: 1.9179999999999998e-9 с
Время создания LowerTriangular: 2.138e-9 с



4.4.4.1. Проверка продуктивности по определению

a) A =


2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

(I-A)^(-1) =


2×2 Matrix{Float64}:
  0.5  -0.333333
 -0.5   0.0

Матрица непродуктивна
Контрпример по определению: y = [1.0, 0.0], x = [0.5, -0.5]

b) A =


2×2 Matrix{Float64}:
 0.5  1.0
 1.5  2.0

(I-A)^(-1) =


2×2 Matrix{Float64}:
  0.5   -0.5
 -0.75  -0.25

Матрица непродуктивна
Контрпример по определению: y = [1.0, 0.0], x = [0.5, -0.75]

c) A =


2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.4

(I-A)^(-1) =


2×2 Matrix{Float64}:
 1.25   0.416667
 0.625  1.875

Матрица продуктивна



4.4.4.2. Критерий неотрицательности (I-A)^(-1)

a) A =


2×2 Matrix{Float64}:
 1.0  2.0
 3.0  1.0

(I-A)^(-1) =


2×2 Matrix{Float64}:
 -0.0  -0.333333
 -0.5   0.0

Матрица непродуктивна

b) A =


2×2 Matrix{Float64}:
 0.5  1.0
 1.5  0.5

(I-A)^(-1) =


2×2 Matrix{Float64}:
 -0.4  -0.8
 -1.2  -0.4

Матрица непродуктивна

c) A =


2×2 Matrix{Float64}:
 0.1  0.2
 0.3  0.1

(I-A)^(-1) =


2×2 Matrix{Float64}:
 1.2  0.266667
 0.4  1.2

Матрица продуктивна



4.4.4.3. Спектральный критерий

a) λ = [-1.4494897427831779, 3.4494897427831783]
Спектральный радиус ρ(A) = 3.4494897427831783
Матрица непродуктивна

b) λ = [-0.7247448713915892, 1.724744871391589]
Спектральный радиус ρ(A) = 1.724744871391589
Матрица непродуктивна

c) λ = [-0.14494897427831785, 0.34494897427831783]
Спектральный радиус ρ(A) = 0.34494897427831783
Матрица продуктивна

d) λ = [0.02679491924311228, 0.1, 0.37320508075688774]
Спектральный радиус ρ(A) = 0.37320508075688774
Матрица продуктивна

Лабораторная работа № 4 выполнена полностью
